#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        #reverting apt disk cache if the file was written at all
        if [ -f /etc/apt/apt.conf.d/02nocache ]; then
            rm /etc/apt/apt.conf.d/02nocache;
            #reverting cron-apt package download
            echo "autoclean -y" >> /etc/cron-apt/action.d/3-download ;
            echo "upgrade -d -y -o APT::Get::Show-Upgraded=true" >> /etc/cron-apt/action.d/3-download ;
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
