#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    dpkg-trigger update-workbench
}

case "$1" in
    purge)
        remove_action

        # remove directories and files
        rm -f /etc/logrotate.d/zram-config
        rm -f /etc/ztab
        rm -f /usr/sbin/fsck.overlay
        rm -f /usr/sbin/overlay
        rm -f /var/log/zram-config
        rm -rf /opt/zram
        rm -rf /usr/lib/zram-config
        rm -rf /usr/local/lib/zram-config
        rm -rf /usr/local/share/zram-config

        # reverting apt disk cache if the file was written at all
        if [ -f /etc/apt/apt.conf.d/02nocache ]; then
            rm /etc/apt/apt.conf.d/02nocache;
            #reverting cron-apt package download
            echo "autoclean -y" >> /etc/cron-apt/action.d/3-download ;
            echo "upgrade -d -y -o APT::Get::Show-Upgraded=true" >> /etc/cron-apt/action.d/3-download ;
        fi
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
