#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
        omv-mkconf flashmemory
        folder2ram -syncall
        folder2ram -disablesystemd
    ;;

    upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
