#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
        # stop and disable service
        /usr/sbin/zram-config stop || :
        deb-systemd-invoke stop zram-config.service || :
        deb-systemd-helper disable zram-config.service
    ;;

    upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
